//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparrow.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public int Id { get; set; }
        public int tipoActividadId { get; set; }
        public int usuarioId { get; set; }
        public string nota { get; set; }
        public System.DateTime fechaHora { get; set; }
    
        public virtual TipoActividad TipoActividad { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
