//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparrow.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public int medidaId { get; set; }
        public int tipoId { get; set; }
        public double stock { get; set; }
        public Nullable<double> alertaStock { get; set; }
    
        public virtual Medida Medida { get; set; }
        public virtual Tipo Tipo { get; set; }
    }
}
